name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build
      uses: lpenz/ghaction-cmake@v0.2
      with:
        directory: xneur
        dependencies: libgstreamer1.0-dev libnotify-dev libenchant-dev libxi-dev libxtst-dev
