name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install libgstreamer1.0-dev libnotify-dev libenchant-dev libxi-dev libxtst-dev
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build
      uses: lpenz/ghaction-cmake@v0.1
      with:
        directory: xneur
